[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['cd backend && pnpm install']

[phases.build]
cmds = ['cd backend && pnpm run build']

[start]
cmd = 'cd backend && pnpm medusa db:migrate && pnpm run start' 