[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'cd backend && pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
  'cd backend && (pnpm run build:railway || pnpm run build:fallback)',
  'echo "Verifying build output..."',
  'ls -la backend/.medusa/ || echo "Build directory not found"',
  'ls -la backend/.medusa/client/ || echo "Client directory not found, admin may be disabled"',
  'echo "Build phase completed"'
]

[start]
cmd = 'cd backend && pnpm medusa db:migrate && pnpm run start' 